import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { inter } from "./components/fonts";
import Header from "./components/header";
import { Toaster } from "./components/ui/sonner";
import FooterContainer from "./components/containers/footer-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${inter.className} antialiased h-screen`}>
        <Header />
        <Toaster position="top-center" />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <div className="mt-20">
          <FooterContainer />
        </div>
      </body>
    </html>
  );
}
