import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { inter } from "./components/fonts";
import { Toaster } from "./components/ui/sonner";
import FooterContainer from "./components/containers/footer-container";
import { cn } from "@/lib/utils";
import HeaderContainer from "./components/containers/header-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={cn(inter.className, `antialiased h-screen scroll-smooth`)}
      >
        <Toaster position="top-center" />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <HeaderContainer />
          {children}
          <div className="mt-20">
            <FooterContainer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
